//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopBrian
{
    using System;
    using System.Collections.Generic;
    
    public partial class dharma_wisdom
    {
        public int wisdom_id { get; set; }
        public int user_id { get; set; }
        public int factor1_level { get; set; }
        public double factor1_hours { get; set; }
        public int factor2_level { get; set; }
        public double factor2_hours { get; set; }
    }
}
