//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopBrian
{
    using System;
    using System.Collections.Generic;
    
    public partial class dharma_concentration
    {
        public int concentration_id { get; set; }
        public int user_id { get; set; }
        public int factor6_level { get; set; }
        public double factor6_hours { get; set; }
        public int factor7_level { get; set; }
        public double factor7_hours { get; set; }
        public int factor8_level { get; set; }
        public double factor8_hours { get; set; }
    }
}
