//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopBrian
{
    using System;
    using System.Collections.Generic;
    
    public partial class dharma_ethicalconduct
    {
        public int ethicalconduct_id { get; set; }
        public int user_id { get; set; }
        public int factor3_level { get; set; }
        public double factor3_hours { get; set; }
        public int factor4_level { get; set; }
        public double factor4_hours { get; set; }
        public int factor5_level { get; set; }
        public double factor5_hours { get; set; }
    }
}
