//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopBrian
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ist420grp5Entities1 : DbContext
    {
        public ist420grp5Entities1()
            : base("name=ist420grp5Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomerBrianTran> tblCustomerBrianTrans { get; set; }
        public virtual DbSet<tblInventoryBrianTran> tblInventoryBrianTrans { get; set; }
    }
}
