//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopBrian
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerTully
    {
        public int fldCustomerID { get; set; }
        public string fldCustomerName { get; set; }
        public string fldCustomerSSN { get; set; }
        public string fldCustomerEmail { get; set; }
        public string fldCustomerPhone { get; set; }
        public Nullable<bool> fldCustomerActive { get; set; }
    }
}
