//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShopBrian
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerBatschelet
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSSN { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<bool> CustomerActive { get; set; }
    }
}
